# Generated by Django 5.0.6 on 2024-07-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oname', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('car', models.CharField(max_length=50)),
                ('carnumber', models.CharField(max_length=50)),
                ('intime', models.TimeField(null=True)),
                ('outtime', models.TimeField(null=True)),
                ('indate', models.CharField(max_length=20)),
                ('outdate', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=40)),
                ('phonenumber', models.IntegerField(null=True)),
                ('password', models.CharField(max_length=20)),
                ('repassword', models.CharField(max_length=20)),
            ],
        ),
    ]
